version: "3.5"

services:
  db:
    image: postgres
    command: postgres -c log_min_messages=FATAL
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5435:5432"